name: slap-cpuonly
channels:
  - conda-forge
dependencies:
  - python=3.7
  - conda-forge::rdkit=2022.09.*
  - scikit-learn=1.0.*
  - conda-forge::py-xgboost=1.5.*
  - seaborn=0.12.*
  - pytorch::pytorch==1.12.0
  - pytorch::torchvision==0.13.0
  - pytorch::torchaudio==0.12.0
  - pytorch::cpuonly
  - pytorch-lightning=1.6.*
  - torchmetrics=0.9.*
  - dglteam::dgl=0.8.*
  - pip
  - pip:
    - dgllife==0.2.9
    - botorch==0.6.4
    - ax-platform==0.2.5.1
    - wandb==0.13.11
    - jupyter
    - git+https://github.com/bp-kelley/descriptastorus
