# common settings
accelerator: cpu  # usually cpu or gpu.

# data
reaction: True
data_name: slap_dataset_reactions.csv
rdkit_features: True  # bool, if True add rdkit features
fingerprints: True  # bool, if True add fingerprints
graph_type: bond_nodes  # str, options: {bond_edges, bond_nodes}. If bond_edges, build graph where atoms->nodes and
                        # bonds->edges. If bond_nodes, both atoms and bonds are encoded as edges.
featurizers: dgllife  # str, featurizers to use for atom and bond features. Options: {dgllife, chemprop}

# model
encoder:
  type: RDKit  # str, options: {D-MPNN, GCN, RDKit, FP}. Note that RDKit and FP will ignore all other encoder configs.

decoder:
  type: Ridge  # str, options: {FFN, Ridge, XGB}.

  # Ridge parameters
  Ridge:
    alpha: 0.1  # float, alpha for Ridge

  # XGBoost parameters
  XGB:
    n_estimators: 100  # int, number of estimators for XGBoost
    learning_rate: 0.1  # float, learning rate for XGBoost
    max_depth: 6  # int, max depth for XGBoost
    gamma: 0.3  # float, for XGBoost:  Minimum loss reduction required to make a further partition on a leaf node of the tree.
    colsample_bytree: 0.5  # float, for XGBoost. Subsample ratio of columns when constructing each tree.
    reg_alpha: 0  # float, L1 regularization for XGBoost
    reg_lambda: 1  # float, L2 regularization for XGBoost

# FFN parameters
optimizer:
  weight_decay: 0
  lr: 0.0002
  lr_scheduler:
    epochs: 100  # should be the same as max_epochs for the desired effect
    lr_min: 0.00002
    lr_warmup_step: 2
    scheduler_name: exp_with_linear_warmup

training:
  max_epochs: 100