# common settings
name: XGB  # str, options: {D-MPNN, GCN, FFN, XGB, LogisticRegression}.
accelerator: cpu  # usually cpu or gpu.

# model
encoder:
    reaction: True
    graph_type: bond_nodes  # str, options: {bond_edges, bond_nodes}. If bond_edges, build graph where atoms->nodes and bonds->edges. If bond_nodes, both atoms and bonds are encoded as edges.
    featurizers: dgllife  # str, featurizers to use for atom and bond features. Options: {dgllife, chemprop}

decoder:
  global_features: FP  # str, options: {"RDKit", "FP", "OHE", "fromFile", None}. Global features to include with the graphs.
  global_features_file: None #data/all_reactant_smiles_delfta_features.json  # str, path to file containing global features. Only used if global_features == "fromFile".
  n_estimators: 100  # int, number of estimators for XGBoost
  learning_rate: 0.1  # float, learning rate for XGBoost
  max_depth: 6  # int, max depth for XGBoost
  gamma: 0.3  # float, for XGBoost:  Minimum loss reduction required to make a further partition on a leaf node of the tree.
  colsample_bytree: 0.5  # float, for XGBoost. Subsample ratio of columns when constructing each tree.
  reg_alpha: 0  # float, L1 regularization for XGBoost
  reg_lambda: 1  # float, L2 regularization for XGBoost
