- bounds:
  - 10
  - 600
  name: hidden_size
  type: range
  value_type: int

- bounds:
  - 3
  - 5
  name: mpnn_depth
  type: range
  value_type: int

- bounds:
  - 1
  - 3
  name: ffn_depth
  type: range
  value_type: int

- bounds:
  - 0.0
  - 0.5
  name: dropout
  type: range
  value_type: float
