- bounds:
  - 1024
  - 8192
  name: encoder_hidden_size
  type: range
  value_type: int

- bounds:
  - 5
  - 8
  name: encoder_depth
  type: range
  value_type: int

- bounds:
  - 0.00001
  - 0.0001
  name: learning_rate
  type: range
  value_type: float
  log_scale: True

#- values:
#  - "attention"
#  - "mean"
#  - "max"
#  - "sum"
#  name: aggregation
#  type: choice
#  value_type: str
