- bounds:
  - 0.01
  - 100
  name: C
  type: range
  value_type: float
  log_scale: True

#- values:
#  - "attention"
#  - "mean"
#  - "max"
#  - "sum"
#  name: aggregation
#  type: choice
#  value_type: str
