- bounds:
  - 16
  - 2048
  name: mpnn_hidden_size
  type: range
  value_type: int

- bounds:
  - 3
  - 6
  name: mpnn_depth
  type: range
  value_type: int

- bounds:
  - 16
  - 128
  name: ffn_hidden_size
  type: range
  value_type: int

- bounds:
  - 1
  - 3
  name: ffn_depth
  type: range
  value_type: int

- bounds:
  - 0.00000001
  - 0.5
  name: dropout
  type: range
  value_type: float
  log_scale: True

- bounds:
  - 0.0001
  - 0.01
  name: learning_rate
  type: range
  value_type: float
  log_scale: True

- values:
  - "attention"
  - "mean"
  - "max"
  - "sum"
  name: aggregation
  type: choice
  value_type: str
